#!/bin/bash
SOURCE_DIR="/path/to/your/source/directory"
DEST_DIR="path/to/destination/directory"
TIMESTAMP=$(date +"%Y%m%d%H%M%S")
#it will store it with timestamp
BACKUP_FILE="$DEST_DIR/backup_$TIMESTAMP.tar.gz"
tar -czf "$BACKUP_FILE" -C "$SOURCE_DIR" .
if [ $? -eq 0 ]; then
        echo "BAckup successful"
else
        echo "BAckup unsuccessful"
fi

